<h2>Pourquoi ces facteurs ? </h2>
<p style="text-align:justify;">Voici quelques uns des facteurs sur lesquels portent l’évaluation du CERP. Ils sont tous issus soit : de la bibliographie scientifique spécialisée ou des retours d’expériences et des connaissances empiriques venant des éleveurs et spécialistes sur le terrain. 
L’explication de ces facteurs a pour objectif de vous permettre de mieux comprendre les résultats de votre évaluation et d’identifier les axes d’amélioration et méthode pour y parvenir à votre portée. Ces explications sont des paroles d’éleveurs, d’écologues, de spécialistes et des explications fournies par la bibliographie.</p>

<h3>Le contexte économique et social </h3> 
<p><b>Le schéma de l’exploitation </b>: Cela donne des informations sur la facilité pour l’exploitant-e de surveiller son exploitation. Il est <i>plus facile</i> d'équiper et d'être vigilant sur une exploitation avec un schéma en O (avec l'exploitation au milieu) que sur une exploitation en T ou L où l'exploitation ne donne pas sur tout le troupeau ou l’ensemble des parcelles. </p>
<p style="text-align: justify;"><b> La taille des parcelles : </b> Les plus grands parcs sont plus difficiles à garder et présentent plus  de risque d’oublier une bête quelque part. Un grand parc favorise la dispersion des animaux et accroît le risque de prédation.  </p> 
<p style="text-align: justify;"><b> La distance du parc à l’exploitation : </b> Un parc plus petit diminue le risque d'attaque, mais il ne devient pas nul pour autant. Par exemple, "en 2014, lors des premières prédations en Centre Meuse, la première réaction avait été de rapprocher les lots des villages ou des exploitations. Une fausse bonne idée confirmée par des attaques à proximité immédiate des habitations. Ce fait ne s'est jamais démenti depuis." De plus, plus les lots sont éloignés, plus il est difficile de percevoir les changements de comportement du troupeau, les problèmes de matériels, etc. Il est aussi plus difficile d'intervenir en urgence sur un ou des lots éloignés de plusieurs kilomètres entre eux ou de l'exploitation.
</p>
<p style="text-align: justify;"><b> L’autonomie fourragère et/ou en céréales : </b> L'autonomie offre plus de marge de manœuvre quant à la gestion du pâturage et donc au risque de prédation. La pratique de la vaine pâture et le pâturage des cultures intermédiaires augmentent ce risque. Cela va jouer sur l'indépendance financière de l'éleveur et ses capacités à prendre les devants et se relever en cas d'attaques non indemnisables/ non indemnisées. </p>
<p style="text-align: justify;"><b> La situation financière de l’exploitation : </b> La situation financière de l'exploitation est sollicitée à deux niveaux : sa trésorerie (en attente des indemnisations "prédation" ou des subventions "moyens de protection") et sa capacité à couvrir les <i>-au moins-</i> 20 % du montant investi dans les moyens de protection et à la charge de l'éleveur.
</p>
<p style="text-align: justify;"><b> Activité économique supplémentaire : </b> L'activité économique supplémentaire à celle de l'élevage est une charge mentale supplémentaire pour les éleveurs. Au-delà des difficultés sociales reconnues inhérentes à une charge mentale trop lourde, l’absence répétée de l’exploitant-e sur sa ferme peut l’empêcher de noter des changements de comportement chez ses bêtes. </p>
<p style="text-align: justify;"><b> Projection à court/moyen/long terme : </b> Une projection à court terme est un projet sur l'année à venir. Un exploitant en cours d'installation ou une exploitation en difficulté qui n'aurait pas de projection à court terme peuvent être plus perturbés par la prédation que des exploitations stables dont la projection peut se faire à court, moyen et même long terme.
</p>
<p style="text-align: justify;"><b> Accompagnement financier : </b> Face aux difficultés et à une charge mentale parfois écrasante, il est plus dur de ne pas être en colère ou profondément en détresse face à la prédation. C'est toujours une agression de voir ses bêtes dévorées ou disparues. Lorsqu'il y a une reconnaissance, et du soutien de la part des consommateurs et de l'état, c'est déjà moins difficile de s'adapter à un contexte de prédation. </p>
<p style="text-align: justify;"><b> Main d’œuvre disponible : </b> Plus la main d'œuvre, bénévole ou salariée, est formée, autonome, responsable, et bienveillante vis-à-vis de l'éleveur <i>(parfois en situation de choc post traumatique après une attaque)</i> plus il est probable qu’elle puisse être efficace. Ce critère ne tient pas compte de la pédagogie ni de la clarté de l’éleveur-se dans ses directives. Néanmoins, ce facteur souligne l’importance de pouvoir s’appuyer sur des personnes volontaires et formées si nécessaire. </p>
<p style="text-align: justify;"><b> Expérience de l’élevage : </b> L'expérience est certainement un atout mais n'est pas suffisante seule pour limiter le risque de prédation. Avoir le sens de l'élevage, la volonté d'adapter son système de production sont des éléments importants. Idéalement avoir l'état d'esprit d'anticiper le retour du loup. En phase d'installation, les problèmes se cumulent souvent dans un contexte économique et financier contraints. </p>
<p style="text-align: justify;"><b> Temps passé sur la ferme depuis que vous êtes chef-fe d’exploitation : </b> Avec le temps et l'expérience sur une même ferme, la connaissance de l'environnement et la capacité d'anticipation tendent à augmenter. </p>
<p style="text-align: justify;"><b> Expérience de la prédation : </b> L'expérience de la prédation induirait une meilleure détection des situations de crise et d'anticipation. L’hypothèse de l’apprentissage par essai-erreur est privilégiée même si une recrudescence de prédation sur une exploitation pourrait aussi souligner un manque d’anticipation et ou détection des pics de prédation. </p>
<p style="text-align: justify;"><b> Formation : </b> La formation à la prédation favorise une meilleure gestion des situations de crise, et facilite l'anticipation. </p>
<p style="text-align: justify;"><b> Quels soutiens mobiliser : </b> Le fait d'être accompagné techniquement participe à une forme de soutien moral également. C'est très important sinon on ne sait pas quoi faire et on le fait mal ou on dépense trop dans des mesures pas forcement pertinentes ! L'accompagnement technique permet de créer une dynamique et d'ouvrir sur d'autres sujets moins "faciles" (accompagnement psychologique, difficultés financières ...). </p>
<p style="text-align: justify;"><b> Soutien moral : </b> Les situations de crises peuvent être générées ou renforcées par la prédation. Les situations de détresse psychologiques sont à prendre au sérieux. Cela est d'autant plus vrai que dans un contexte de prédation, le phénomène d'isolement est renforcé et la vulnérabilité des personnes comme des exploitations est accentuée. L'intervention de professionnels, bénévoles ou proches bienveillants peut aider l'exploitant-e et son entourage à résister aux crises. </p>
<p style="text-align: justify;"><b> Handicap : </b> Les douleurs ou une invalidité peuvent, selon leur importance et les zones touchées, entraver l'activité physique impliquée dans la pratique de l'élevage (e.g. gardiennage, travaux de rafraichissement des clôtures, chantiers, etc.). Il apparait alors plus compliqué de faire face à des situations de prédation seul-e. </p>


<p style="text-align: justify;"><b> Situation personnelle : </b> Des difficultés vécues dans la vie personnelle perturbent l'équilibre avec la vie professionnelle. Cet équilibre lorsqu'il est rompu, favorise les situations de crise et réduisent les capacités à détecter, agir, etc. </p>
<h3> Elevage  </h3>
<p style="text-align: justify;"><b> L’élevage de plein air : </b> L’élevage en plein air est plus exposé du fait de son accessibilité. </p>
<p style="text-align: justify;"><b> Pâturage libre : </b> Le pâturage libre favorise la dispersion des bêtes ce qui rend le troupeau plus difficile à garder et plus facile à attaquer. </p>
<p style="text-align: justify;"><b> Fréquence des visites pour un même lot : </b> L’activité humaine réduit généralement le risque de prédation car elle a tendance à effaroucher le prédateur. Plus l’activité est importante autour des parcs, plus le risque de prédation diminue. Si le risque diminue avec le nombre de visite mais <u>ne devient jamais nul pour autant</u>. </p>
<p style="text-align: justify;"><b> Nombre de bêtes sur l’exploitation : </b> Plus il y a de bêtes sur l’exploitation, plus il est difficile de toutes les connaître. Il est aussi plus difficile de maîtriser un grand troupeau plus enclin à transmettre des comportements, maladies, etc. "Plus le troupeau est grand, moins il y a d'individualisme. Les mouvements de troupeaux (paniques, etc.) sont plus forts et moins contrôlables avec de grands troupeaux". </p>
<p style="text-align: justify;"><b> Nombre de lots différents en simultanée : </b> Plus il y a de lots, plus c'est difficile de tout protéger. Cela accroît notamment la charge mentale et contribue à réduire la vigilance de l’éleveur-euse ou berger-ère.  </p>
<p style="text-align: justify;"><b> Nombre d’animaux par lot : </b> Il est plus aisé de surveiller de petits lots. Ainsi, moins le nombre de bêtes est élevé dans un lot, moins elles sont difficiles à protéger. Le nombre d’animaux par lot implique un risque de fréquence et de gravité. Un lot de plus petite taille, plus facile à garder, est moins exposé à un risque de fréquence qu’un lot de grande taille où certains animaux peuvent être à l’écart sans que cela se remarque. En revanche, un lot de grande taille est moins exposé à un risque de gravité qu’un lot de petite taille (e.g. si le prédateur tue 15 bêtes, l’éleveur-euse en ayant 100 sera plus impacté économiquement que celui en ayant 500). </p>
<p style="text-align: justify;"><b> Ratio entre la taille de votre cheptel et l'UTH (Unité de temps Humain) : </b> Plus il y a de bêtes par UTH, moins l'éleveur-euse ou le berger-ère "connaît" ses bêtes. Les soins sont moins personnalisés et il est plus compliqué de détecter des changements dans l'attitude de certains individus ou du troupeau pouvant indiquer une prédation à venir. </p>
<p style="text-align: justify;"><b> Regroupement nocturne : </b> Le troupeau est plus facile à surveiller, et le regroupement complique la prédation car il y a moins de bête isolées. </p>
<p style="text-align: justify;"><b> Regroupement nocturne en abri : </b> Diminue le risque car le regroupement des animaux en abri est potentiellement effarouchant. De plus, l’imperméabilité de l’abri peut constituer une barrière impénétrable pour le prédateur. </p>
<p style="text-align: justify;"><b> Cabanes de mises bas : </b> Les cabanes de mise bas permettent une protection même provisoire des mères et des petits pendant leur pic de vulnérabilité. Une cabane ne saurait être efficace que si elle est en bon état et imperméable aux prédateurs. </p> 
<p style="text-align: justify;"><b> Naissance en extérieur : </b> Les placentas, les juvéniles et les mères vulnérables en période de mise bas (éloignement du troupeau, faible mobilité, peu d’énergie, etc.) attirent les prédateurs. Les odeurs plus fortes du couple mère/jeune et les vocalises contribuent également à attirer les prédateurs. </p>
<p style="text-align: justify;"><b> Abri fermé dans la pâture : </b> Permet d'avoir un point de regroupement qui sert de repère en cas de perturbation. Cela peut aussi faciliter le travail du gardien humain ou non humain.  </p>
<p style="text-align: justify;"><b> Temps passé sur un même parc de pâturage : </b> Plus le temps de résidence sur une pâture est long, plus les prédateurs ont le temps d’observer et attaquer. De plus, le pâturage prolongé peut induire un surpâturage rendant moins attrayante la pâture et qui accroît la probabilité que les bêtes s'échappent de la parcelle. </p>
<p style="text-align: justify;"><b> Retrait des déchets et carcasses : </b> La présence de carcasses attire les prédateurs. </p>
<p style="text-align: justify;"><b> Distribution des points d’eau : </b> L'absence de point d'eau en dehors du parc de pâturage peut favoriser l'intrusion de la faune sauvage, voir des prédateurs. Cette perturbation peut stresser le troupeau, influencer sa santé, sa vulnérabilité à la prédation. </p>
<p style="text-align: justify;"><b> Situation du point d'eau dans le parc : </b> Les points d’eau peu accessibles où la vue n’est pas dégagée peuvent favoriser l’approche discrète d’un prédateur et bloquer la fuite du bétail. Il apparaît important de placer les zones d’abreuvement là où la vue est dégagée et la fuite facilitée. Cela permettra notamment aux bêtes de donner l’alerte en plus de fuite et appuiera le travail du/des gardiens. </p>
<p style="text-align: justify;"><b> Espèce élevée : </b> Les sensibilités entre les espèces peuvent réduire ou accroître le risque de prédation. Globalement, les petits ruminants sont les plus exposés à la prédation ce qui n'écarte par la vulnérabilité d'autres types d'élevage (bovin, équin, etc.). </p>
<p style="text-align: justify;"><b> Objectif de production : </b> La filière lait est moins exposée car les bêtes sont rentrées 1 à 2 fois par jour. Les éleveurs connaissent généralement mieux leurs animaux pour les côtoyer plus régulièrement. </p>
<p style="text-align: justify;"><b> Nombre de jeunes par mère : </b> Plus une mère a de petit et moins son attention est focalisée sur chacun d’entre eux et plus le risque de voir disparaître les petits où la mère augmente. </p>
<p style="text-align: justify;"><b> Sons émis par les animaux : </b> Bien que le comportement des bêtes puisse alerter sur une situation de prédation, les sons émis, notamment chez un troupeau habituellement silencieux, sont un indicateur important. </p>
<p style="text-align: justify;"><b> Réaction des bêtes face à une perturbation : </b> Des bêtes farouches et éparpillées dans une parcelle s'exposent plus à la prédation. Les troupeaux grégaires ayant le réflexe de se regrouper en cas de perturbation sont plus faciles à protéger et plus difficiles à attaquer pour un prédateur.  </p>
<p style="text-align: justify;"><b> Attitudes des bêtes face à l’éleveur-euse/berger-ère : </b> Une relation apaisée entre un-e éleveur-euse ou un-e berger-ère et ses animaux favorise de comportements et situations inhabituelles. Cela favorise également le retour au calme du troupeau après un évènement inhabituel/stressant. La détérioration brutale de l'attitude du troupeau à l'égard de son/sa gardien-ne est un indicateur de perturbation à prendre en compte, notamment dans un contexte de prédation. </p>
<p style="text-align: justify;"><b> Comportement des bêtes : </b> Les animaux stressés ou en mauvaise santé sont plus vulnérables soient à cause des odeurs qu’ils diffusent, de la prostration, du retrait du troupeau, etc. </p>
<p style="text-align: justify;"><b> Difficultés à se déplacer : </b> Des bêtes faibles, malades ou blessées sont des cibles plus faciles pour les prédateurs. Elles sont également souvent un peu à l'écart du troupeau donc facilement isolées ou oubliées. </p>
<h3>Moyens de protection </h3>
<p style="text-align: justify;"><b> Type de parc : </b> Le type de parc a une influence sur la prédation. Le parc a une fonction de protection physique et peut décourager et/ou empêcher les prédateurs d’accéder au bétail à l’intérieur. </p>
<p style="text-align: justify;"><b> Type de clôture : </b> Les clôtures, comme le type de parc, ont une influence sur l'accès des prédateurs au troupeau. Plus la clôture est difficile à passer, plus le risque de traverser la clôture diminue. Ainsi, une clôture haute et électrifiée réduit l'exposition à la prédation alors que l'absence de clôture ou des clôtures très basses, l'augmente et renforce le comportement du prédateur. </p>
<p style="text-align: justify;"><b> Hauteur de clôture : </b> Une clôture haute est moins franchissable qu'une clôture basse au-dessus de laquelle il est aisé de sauter. </p>
<p style="text-align: justify;"><b> État des clôtures : </b> L'état des clôtures du parc est déterminant quant à son efficacité. Un parc électrique avec combinaison de clôtures fixes et mobiles ou semi mobiles peut ne pas être efficace dans le cas où les clôtures sont dégradées ou si l'électricité n'est pas suffisamment constante ou puissante. </p>
<p style="text-align: justify;"><b> Motivation à mettre en place des moyens de protection : </b> La volonté d'adapter son système de production est un élément important sinon primordial. Avoir l'état d'esprit d'anticiper le retour du loup implique une certaine volonté. Cela est d'autant plus vrai en phase d'installation car les problèmes se cumulent souvent dans un contexte économique et financier contraint. </p>
<p style="text-align: justify;"><b> Disponibilité des protections d’urgence : </b> La disponibilité des protections d'urgence favorise la réponse et l'anticipation à des évènements de prédation. Même si ces méthodes ne sont pas viables à long terme, elles favorisent l'effarouchement et le détournement de la prédation ponctuellement. </p>
<p style="text-align: justify;"><b> Système d’alarme localisé disponible : </b> La mise en place d'un système d'alarme localisé et utilisé à bon escient facilite l'anticipation des éleveur-euses et berger-ères en cas de prédation à proximité. Cela leur permet notamment d'augmenter le nombre de visites du troupeau, de rassembler les lots, etc. </p>
<p style="text-align: justify;"><b> Mise en place de tirs : </b> Les tirs n’ont pas tous le même impact sur la prédation. Le tir d’effarouchement est à considérer comme une protection d’urgence peu pérenne en raison de l’habituation des prédateurs. Parmi les tirs létaux, les tirs de défense sont appropriés dans le sens où ils répondent à un évènement de prédation « sur le fait ». Attention cependant, « l’apprentissage de la peur » au loup n’est pas prouvé et fait plutôt débat. Le loup n’associe pas forcément l’évènement traumatique à l’attaque du troupeau mais peut simplement être associé à la présence humaine d’où l’intérêt d’installer un tryptique de protection (gardiennage humain + chiens de protection + clôtures adaptées). Les tirs de prélèvements quant à eux sont non sélectifs et peuvent faire augmenter le stress dans les meutes, résultant en des comportements d’agressivité pouvant faire éclater les meutes en plusieurs disperseurs favorisant à long terme le risque de prédation.  </p>
<p style="text-align: justify;"><b> Gardien humain : </b> La présence d’un gardien expérimenté jour et nuit diminue grandement le risque de prédation. Pour être le plus efficace possible, ce gardien doit être formé aux mesures de protection afin de garantir les meilleurs comportements d’anticipation et de réponse à la prédation. </p>
<h3>Environnement </h3>
<p style="text-align: justify;"><b> Présence de tourisme/loisir dérangeant autour de l’exploitation ou du parc de pâturage : </b> La fréquentation de sites à proximité des parcs de pâturage peut avoir un effet effarouchant. Sans être un critère décisif dans les évènements de prédation, la présence humaine aléatoire sur certains sites de tourisme notamment constitue un frein important à la prédation.</p>
<p style="text-align: justify;"><b> Météorologie dominante à l’année : </b> Les attaques sur les troupeaux sont facilitées par des conditions météorologiques défavorables (pluie, brouillard, etc.). S’il n’est pas possible d’agir sur la météorologie, en revanche, la connaissance des conditions annuelles sur une parcelle ou l’exploitation permet de s’organiser quant à la mise en pâturage. 
</p><p style="text-align: justify;"><b> Cours d’eau à proximité : </b> Un cours d'eau est difficile à clôturer, surtout en présence de ripisylve. Les bandes enherbées attenantes au cours d'eau sont des couloirs de circulation et potentiellement un garde-manger lorsqu'elles sont pâturées. Les cours d'eau à sec en été sont des corridors privilégiés alors même que les grands cours d'eau peut voir infranchissables et réduisent l'exposition du troupeau à la prédation. </p>
<p style="text-align: justify;"><b> Type de sol : </b> Le temps séchant (chaleur, vent, etc.) complique la pose des clôtures mobiles et nuit à la qualité de la prise de terre. Le vent incline sérieusement les filets. L'excès d'eau déstabilise les piquets. </p>
<p style="text-align: justify;"><b> Objet remarquables dans le pâturage (objets imposants, rochers, tas de bois, etc.) et niveau d’embroussaillement : </b> Les prédateurs peuvent se dissimuler. Plus le nombre d'objets remarquables augmente, plus le risque d'exposition augmente également. </p>
<p style="text-align: justify;"><b> Relief : </b> Les pentes rocheuses sont dangereuses pour les troupeaux. Un relief prononcé donne également plus de possibilités de se cacher pour les prédateurs. </p>
<p style="text-align: justify;"><b> Période de pâturage : </b> Certaines périodes sont plus sensibles pour les prédateurs. En période d'allaitement et de soins aux jeunes, les besoins énergétiques augmentent ce qui peut exposer plus fortement à la prédation. De la même façon, lors de l'émancipation des jeunes, ces derniers apprennent à chasser pour devenir autonomes. Les troupeaux domestiques n'étant pas sélectionnés pour faire face à la prédation et étant globalement plus vulnérables et faciles à chasser que les espèces sauvages, ils sont plus exposées à la prédation. </p>
<p style="text-align: justify;"><b> Distance de l’exploitation/ des pâturages au dernier foyer de prédation sur bétail domestique : </b>  Bien que certaines espèces telles que le loup soient extrêmement mobiles, l'exposition à la prédation réduit à mesure que la distance à la dernière exploitation attaquée augmente.  </p>
<p style="text-align: justify;"><b> </b> </p>
<p style="text-align: justify;"><b> Attitude du prédateur au contact de l’humain : </b> L'absence de fuite en voyant l'humain correspond à une habituation ou à une peur modérée. Cette tolérance peut réduire l'efficacité des moyens de protection et de l’effarouchement impliquant les activités humaines.
</p>
<p style="text-align: justify;"><b> Cercle : </b> Les cercles prévus dans le cadre du PNA Loup et activités d’élevage sont liés à la fréquence des évènements de prédation. Ce classement donne une information reconnue quant au risque de prédation sur une exploitation. Cependant, être dans le Cercle 0 ne signifie pas s'exposer à une attaque imminente, et ne pas être dans l'un des cercles ne signifie pas qu'un évènement de prédation lié au loup est à exclure. </p>




